<a href="https://colab.research.google.com/github/202201617/2022/blob/main/final_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#행렬
A = [[2,7], [3, 4], [6, 1]]
print(len(A))
print(A[0])
print(len(A[0]))

3
[2, 7]
2


In [2]:
#행렬의 원소곱
A = [[2,7], [3, 4], [6, 1]]
B = [[1,4], [4, -1], [2, 5]]

def element_product(A, B):
  C = []
  m = len(A)
  n = len(A[0])
  for i in range(m):
    D = []
    for j in range(n):
      value = A[i][j]*B[i][j]
      D.append(value)
    C.append(D)
  
  return C

C = element_product(A,B)
print(C)

[[2, 28], [12, -4], [12, 5]]


In [3]:
# 행렬곱
A = [[2,7], [3,4], [6,1]]
B = [[3, -3, 5], [-1, 2, -1]]

print(len(A))
print(len(A[0]))
print(len(B[0]))

def matrix_mul(A,B):
  C = []
  m = len(A)
  p = len(A[0])
  n = len(B[0])
  for i in range(m):
    D = []
    for j in range(n):
      sum_k = 0
      for k in range(p):
        sum_k += A[i][k]*B[k][j]
      D.append(sum_k)
    C.append(D)
  return C

C = matrix_mul(A,B)
print(C)

3
2
3
[[-1, 8, 3], [5, -1, 11], [17, -16, 29]]


In [4]:
#Ax=b 풀기
A = [[1, -1, 2, 1], [5, 8, 6, 3], [4, 2, 5, 3], [3, 2, 1, 4]]
B = [2, 10, 3, 1]
x = list(range(0,4)) #[0,1,2,3]

In [5]:
#Ax=b 풀기
A = [[1, -1, 2, 1], [5, 8, 6, 3], [4, 2, 5, 3], [3, 2, 1, 4]]
b = [2, 10, 3, 1]
x = list(range(0,4)) #[0,1,2,3]

#forward elimination (upper triangular matrix)
for k in range(0,3):
  for i in range(k+1, 4):
    mult = A[i][k]/A[k][k]
    for j in range(k,4):
      A[i][j] = A[i][j] - mult*A[k][j]
    b[i] = b[i]-mult*b[k]

print(A)
print(b)
print('='*20)

#Back substitution
x[3] = b[3]/A[3][3]
for i in range(2, -1, -1):
  sum_j = 0
  for j in range(i+1, 4):
    sum_j += A[i][j]*x[j]
  x[i] = (b[i] - sum_j)/A[i][i]

print('x=', x)

[[1, -1, 2, 1], [0.0, 13.0, -4.0, -2.0], [0.0, 0.0, -1.1538461538461537, -0.07692307692307687], [0.0, 0.0, 0.0, 1.9999999999999998]]
[2, 0.0, -5.0, 10.000000000000002]
x= [-9.000000000000004, 2.0000000000000004, 4.000000000000001, 5.000000000000002]


In [6]:
def solve(A,b):
  n = len(A)
  for k in range(0,n-1):
    for i in range(k+1, n):
      mult = A[i][k]/A[k][k]
      for j in range(k,n):
        A[i][j] = A[i][j] - mult*A[k][j]
      b[i] = b[i]-mult*b[k]

  x[n-1] = b[n-1]/A[n-1][n-1]
  for i in range(n-2, -1, -1):
    sum_j = 0
    for j in range(i+1, n):
      sum_j += A[i][j]*x[j]
    x[i] = (b[i] - sum_j)/A[i][i] 

  return x

x = list(range(0,3))
A = [[1, -1, 2],
    [5, 8, 6],
    [4, 2, 5]]
b = [2, 10, 3]
x = solve(A,b)

print(x)

[-5.333333333333334, 1.3333333333333335, 4.333333333333334]


In [7]:
#np.array 이용하여 행렬 계산하기
import numpy as np

A = np.array([[2,7], [3,4], [6,1]])
B = np.array([[1,4], [4, -1], [2,5]])
m = len(A)
n = len(A[0])

#행렬 덧셈, 뺄셈, 곱셈, 스칼라곱, 원소곱, 행렬곱
print(A+B)
print(A-B)
print(2*A)
C = np.multiply(A,B) #원소곱
print(C)
print( )

A = np.array([[2,7], [3,4], [6,1]]) #3*2
B = np.array([[3,-3,5], [-1,2,-1]]) #2*3
C = np.matmul(A,B) #행렬곱
print(C)
print( )

#transpose A^T
A = np.array([[3,-3,5], [-1,2,1], [2,4,5]])
At = np.transpose(A)
print(At)
print( )

#diagonal matrix
D = np.diag(A) #diagonal elements → array
print(D)
print( )
 
D2 = np.diag(np.diag(A))
print(D2)

[[ 3 11]
 [ 7  3]
 [ 8  6]]
[[ 1  3]
 [-1  5]
 [ 4 -4]]
[[ 4 14]
 [ 6  8]
 [12  2]]
[[ 2 28]
 [12 -4]
 [12  5]]

[[ -1   8   3]
 [  5  -1  11]
 [ 17 -16  29]]

[[ 3 -1  2]
 [-3  2  4]
 [ 5  1  5]]

[3 2 5]

[[3 0 0]
 [0 2 0]
 [0 0 5]]


In [8]:
import numpy as np

#Identity matrix
I = np.identity(3)
print(I)
print( )

#Upper/lower triangular matrix
A = np.array([[3,-3,4], [-1,2,-1], [2,4,5]])
U = np.triu(A)
print(U)
#L = np.trill(A)
#print(L)
print( )

#determinant/inverse/x=A^-1*b
A = np.array([[1.0, -1.0, 2.0], [5.0, 8.0, 6.0], [4.0, 2.0, 5.0]])
D = np.linalg.det(A)
print(D)

Ainv = np.linalg.inv(A)
print(Ainv)
print( )

#Ax=b → x=A^-1*b
b = np.array([2, 10, 3])
Ainv = np.linalg.inv(A)
x = np.matmul(Ainv, b)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 3 -3  4]
 [ 0  2 -1]
 [ 0  0  5]]

-15.000000000000007
[[-1.86666667 -0.6         1.46666667]
 [ 0.06666667  0.2        -0.26666667]
 [ 1.46666667  0.4        -0.86666667]]

[-5.33333333  1.33333333  4.33333333]


In [9]:
#구글 Drive 연동 & 현재 directory 설정
#colab에서 google drive와 연결
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/2023-1st/')

Mounted at /content/drive


In [10]:
#파일 생성하기 'w'

f = open('Newfile.txt', 'w') #write
for i in range(1, 11):
  data = '%d번째 줄입니다.\n'%i
  f.write(data)
f.close()

In [11]:
#파일 읽기 'r'
#readline 함수: 가장 첫번째 줄이 화면에 출력
f = open('Newfile.txt', 'r') #read
line = f.readline()
print(line)
f.close()

f = open('Newfile.txt', 'r')
lines = f.readlines()
#print(lines) #문자열로 구성된 리스트
for line in lines: #한줄씩 읽고 싶을 때
  print(line)
f.close()

f = open('Newfile.txt', 'r')
data = f.read()
print(data)
f.close()

1번째 줄입니다.

1번째 줄입니다.

2번째 줄입니다.

3번째 줄입니다.

4번째 줄입니다.

5번째 줄입니다.

6번째 줄입니다.

7번째 줄입니다.

8번째 줄입니다.

9번째 줄입니다.

10번째 줄입니다.

1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.



In [12]:
#파일 내용 추가 'a'
f = open('Newfile.txt', 'a') #추가 모드
for i in range(11, 20):
  data = '%d번째 줄입니다.\n'%i
  f.write(data)
f.close()

In [13]:
#Exercise
import random

f = open('lotto.txt', 'a')
num = input('횟수를 입력해주세요: ')

for i in range(int(num)):
  lotto = random.sample(range(1, 46), 6)
  print(lotto)
  f.write(str(lotto) + '\n')
f.close()

횟수를 입력해주세요: 1
[43, 39, 19, 11, 29, 17]


In [14]:
#with문 사용하기
f = open('Newfile2.txt', 'w')
f.write('life is beautiful.')
f.close()

with(open('Newfile2.txt', 'w')) as f:
     f.write('life is beautiful.\n')

# Exercise: with 사용
with open('Newfile2.txt', 'r') as f:
  line = f.readline()
  print(line)
  lines = f.readlines()
  for line in lines:
    print(line)
  data = f.read()
  print(data)

# 내용 추가
with open('Newfile2.txt', 'a') as f:
  f.write('enjoy your life.\n')

life is beautiful.




In [15]:
#예제: 랜덤하게 100명의 키와 몸무게 만들기
import random
hangle = list('가나다라마바사아자차카타파하')

with open('Newfile3.txt', 'w') as f:
  for i in range(10):
    name = random.choice(hangle) + random.choice(hangle)
    weight = random.randrange(40, 100)
    height = random.randrange(140, 200)
    f.write('{}, {}, {}\n'.format(name, weight, height))

In [16]:
#예제: 파일 한 줄씩 읽기
with open('Newfile3.txt', 'r') as f:
  for line in f:
    (name, weight, height) = line.strip().split(', ') #세 개의 문자열(이름, 몸무게, 키)로 구성된 list
    if (not name) or (not weight) or (not height):
      continue

    bmi = int(weight)/((int(height)/100)**2)
    if bmi >= 25:
      result = '과체중'
    elif bmi >= 18.5:
      result = '정상체중'
    else:
      result = '저체중'
    print('\n'.join(['이름: {}', '몸무게: {}', '키: {}', 'bmi: {}', '결과: {}\n']).format(name, weight, height, bmi, result))

이름: 바사
몸무게: 54
키: 193
bmi: 14.49703347740879
결과: 저체중

이름: 바마
몸무게: 50
키: 186
bmi: 14.452537865649207
결과: 저체중

이름: 아가
몸무게: 81
키: 187
bmi: 23.163373273470786
결과: 정상체중

이름: 카차
몸무게: 70
키: 167
bmi: 25.099501595611173
결과: 과체중

이름: 타차
몸무게: 64
키: 155
bmi: 26.638917793964616
결과: 과체중

이름: 사자
몸무게: 67
키: 191
bmi: 18.36572462377676
결과: 저체중

이름: 카카
몸무게: 61
키: 182
bmi: 18.41565028378215
결과: 저체중

이름: 사다
몸무게: 91
키: 182
bmi: 27.47252747252747
결과: 과체중

이름: 마하
몸무게: 67
키: 149
bmi: 30.178820773839018
결과: 과체중

이름: 하라
몸무게: 74
키: 185
bmi: 21.62162162162162
결과: 정상체중



In [17]:
#CSV란, Comma-seperated values의 줄임말로, 쉼표로 정보가 구분되어져 있는 파일을 의미함.
#CSV란 정보가 콤마로 구분되어져 있다는 개념 뿐이고 실제로 CSV이지만, csv가 아닌 txt로 저장되어 있는 경우도 종종 있음
#엑셀이 깔려져 있는 컴퓨터에서는 .csv파일들을 엑셀로 기본으로 보여줌

import csv

#파일 쓰기
data = [
    ['id', 'name', 'price', 'amount'],
    ['1', 'apple', '5000', '5'],
    ['2', 'pencil', '500', '42'],
    ['3', 'pineapple', '8000', '5'],
    ['4', 'pen', '1500', '10']]

f = open('data.csv', 'w')
g = csv.writer(f)
g.writerows(data)
f.close()

In [18]:
#파일 읽기
#for 문으로 reader를 읽어들이면 각 행을 콤마로 구분한 리스트를 불러옴
f = open('data.csv', 'r')
g = csv.reader(f)
for row in g:
  print(row)
f.close()

#data 변수에는 2차원의 리스트로 저장
f = open('data.csv', 'r')
g = csv.reader(f)
data = list(g)
print(data)

['id', 'name', 'price', 'amount']
['1', 'apple', '5000', '5']
['2', 'pencil', '500', '42']
['3', 'pineapple', '8000', '5']
['4', 'pen', '1500', '10']
[['id', 'name', 'price', 'amount'], ['1', 'apple', '5000', '5'], ['2', 'pencil', '500', '42'], ['3', 'pineapple', '8000', '5'], ['4', 'pen', '1500', '10']]


In [19]:
#파일 추가
f = open('data.csv', 'a')
g = csv.writer(f)
g.writerow(['5', 'banana', '2000', '5'])
f.close()

In [20]:
# dictionary 형태로 주어진 파일 쓰고 읽기
# 위 방법들의 단점은 각 행이 리스트로 표현되다 보니 각 행별로 뜯어서 보면 몇번째 항목이 무슨 항목을 의미하는 것인지 직관적으로 알 수 없다.
# 만약, 데이터를 알기 쉽게 딕셔너리의 형태로 제공했다면?
'''
[
    {'id': '1', 'name': 'apple', 'price': '5000', 'amount': '5'},
    {'id': '2', 'name': 'pencil', 'price': '500', 'amount': '42'},
    {'id': '3', 'name': 'pineapple', 'price': '8000', 'amount': '5'},
    {'id': '4', 'name': 'pen', 'price': '1500', 'amount': '10'}
]
'''

"\n[\n    {'id': '1', 'name': 'apple', 'price': '5000', 'amount': '5'},\n    {'id': '2', 'name': 'pencil', 'price': '500', 'amount': '42'},\n    {'id': '3', 'name': 'pineapple', 'price': '8000', 'amount': '5'},\n    {'id': '4', 'name': 'pen', 'price': '1500', 'amount': '10'}\n]\n"

In [21]:
import csv

import csv

keys = ['id', 'name', 'price', 'amount']
data = [
    {'id': '1', 'name': 'apple', 'price': '5000', 'amount': '5'},
    {'id': '2', 'name': 'pencil', 'price': '500', 'amount': '42'},
    {'id': '3', 'name': 'pineapple', 'price': '8000', 'amount': '5'},
    {'id': '4', 'name': 'pen', 'price': '1500', 'amount': '10'}
]

f = open("data2.csv", "w")
g = csv.DictWriter(f, fieldnames = keys)
g.writeheader() #이 부분을 제거하면 파일을 저장할 때 항목 이름이 작성되지 않음
g.writerows(data)
f.close() 

In [23]:
#(1)data4.csv 파일 만들기/읽기
with open('data4.csv', 'w') as f:
  g = csv.DictWriter(f. fieldnames = keys)
  g.writeheader()
  g.writerows(data)

#with open('data4.csv', 'r') as f:
#g = csv.DictReader(f)
#data = list(g)

#(2) average 추가해서 파일 업데이트 시키기
#dict1 = data[0]
#print(dict1)
#average = (float(dict1['kor']))+float(dict1['eng'])+float(dict1['math']))/3
#dict1['average'] = str(round(average,2))
#print(dict1)

AttributeError: ignored

In [24]:
with open('data4.csv', 'r') as f:
  g = csv.DIctReader(f)
  data2 = data

  for dict1 in g:
    dict1 = data[0]
    average = (float(dict1['kor']) + float(dict1['eng']) + float(dict1['math']))/3
    data2[i]['average'] = round(average,2)
    i += 1

#(3) data4.csv 파일 다시 쓰기
keys = ['id', 'kor', 'eng', 'math', 'average']
with open('data5.csv', 'w') as f:
  g = csv.DictWriter(f, fieldname = keys)
  g.writerheader()
  g.writerow(data2)

AttributeError: ignored

In [25]:
#Module(모듈): 함수, 변수, 클래스를 모아 놓은 파일

#module: math
import math

print(math.sin(1))
print(math.cos(1))
print(math.ceil(1.5))
print(math.floor(1.5))

#round는 정수가 홀수일 때 올리고, 정수가 짝수일 때 내림
#round는 반올림 함수가 아님 → 사용할 일이 거의 없음
print(round(1.5))
print(round(2.5))

#from 모듈 이름 import 가져오고 싶은 함수 또는 변수
from math import sin, cos, tan, floor, ceil

#from 모듈 이름 import * (모듈 내부의 모든 것을 다 가져옴)
# → 식별자 이름에서 충돌 발생할 수 있음
# → 최대한 필요한 것만 가져와서 사용하는 것이 좋음

#import 모듈이름 as 사용하고 싶은 식별자
import math as m
print(m.sin(1))
print(m.cos(1))
print(m.ceil(1.5))
print(m.floor(1.5))

0.8414709848078965
0.5403023058681398
2
1
2
2
0.8414709848078965
0.5403023058681398
2
1


In [26]:
#module: random
import random as rn

#random(): 0 <= x < 1 사이의 float로 리턴
print(rn.random())

#uniform(min, max): 지정한 범위 사이의 float를 리턴
print(rn.uniform(0, 10))

#randrange(): 지정한 범위의 int를 리턴
print(rn.randrange(0, 10))

#choice(list): 리스트 내부 요소를 랜덤하게 선택
print(rn.choice([1,2,3,4,5]))

#shuffle(list): 리스트 내부 요소를 랜덤하게 섞음
a = [1,2,3,4,5]
rn.shuffle(a)
print(a)

#sample(list, k=숫자):
print(rn.sample([1,2,3,4,5], 2))

0.3216461798894844
5.562912060927703
8
3
[3, 5, 1, 4, 2]
[5, 2]


In [27]:
#module: os
#colab에서 google drive와 연결
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/2023-1st/')

print(os.name) #현재 운영체제
print(os.getcwd()) #현재 폴더
print(os.listdir()) #현재 폴더 내부요소

#폴더 제거하고 만들기
os.mkdir('New_folder')
os.rmdir('New_folder')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
posix
/content/drive/MyDrive/2023-1st
['전산수학 1-1.ipynb', '전산수학 과제(3 10)', '전산수학 1-2', '전산수학 2-1', '전산수학 2-2', '전산수학 4-1', '전산수학 3-1', '전산수학 3-2', '전산수학 4-2', '전산수학 5-1', '전산수학 7-2', 'Newfile.txt', 'lotto.txt', 'Newfile2.txt', 'Newfile3.txt', 'data.csv', 'data2.csv', '전산수학 10-1.ipynb', '전산수학 9-2', '전산수학 11-1', 'dd', 'New_folder5', 'kma.csv', '12-1.ipynb', 'final test', 'data4.csv']


In [28]:
#파일을 생성하고 파일 이름을 변경
with open('test10.txt', 'w') as f:
  f.write('지금은 테스트 중입니다.')

os.rename('test10.txt', 'new.txt')

#파일 제거하기
os.remove('new.txt')
#os.unlink('new.txt') #어느 것을 사용해도 무방함

#현재 디렉터리를 읽어들이고 디렉터리(폴더)인지 구분하기
output = os.listdir()
for item in output:
  if os.path.isdir(item):
    print('폴더:', item)
  else:
    print('파일:', item)
print('='*20)

#폴더의 요소 읽어들이기
def reader_folder(path):
  output = os.listdir(path)
  for item in output:
    if os.path.isdir(item):
      reader_folder(item)
    else:
      print('파일:', item)


print(os.getcwd())

os.mkdir('New_folder5')
file_path = '/content/drive/MyDrive/2023-1st/New_folder5/test5.txt'
with open(os.path.join(file_path), 'w') as f:
  f.write('지금은 테스트 중 입니다')

reader_folder('.')

파일: 전산수학 1-1.ipynb
파일: 전산수학 과제(3 10)
파일: 전산수학 1-2
파일: 전산수학 2-1
파일: 전산수학 2-2
파일: 전산수학 4-1
파일: 전산수학 3-1
파일: 전산수학 3-2
파일: 전산수학 4-2
파일: 전산수학 5-1
파일: 전산수학 7-2
파일: Newfile.txt
파일: lotto.txt
파일: Newfile2.txt
파일: Newfile3.txt
파일: data.csv
파일: data2.csv
파일: 전산수학 10-1.ipynb
파일: 전산수학 9-2
파일: 전산수학 11-1
폴더: dd
폴더: New_folder5
파일: kma.csv
파일: 12-1.ipynb
파일: final test
파일: data4.csv
/content/drive/MyDrive/2023-1st


FileExistsError: ignored

In [29]:
#module: urllib 모듈
from urllib import request

#urlopen()함수로 링크 열기
target = request.urlopen('https://google.com')
output = target.read()
print(output)

b'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="nl"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="n9YahNq_Qq-_0q4pvQTn6g">(function(){var _g={kEI:\'o4VvZN6nHanjkgX7qYPoAw\',kEXPI:\'0,18167,1341242,6059,206,4804,896,1420,383,246,5,1129120,1704,1196070,117,303071,77529,16114,28684,22430,1362,12311,17588,4998,15066,2009,38444,889,1983,2891,3926,7828,606,58287,2403,2614,3783,9708,230,20583,4,1528,2304,38934,3191,13660,4437,9357,7429,5809,2548,4094,7596,1,42157,2,14019,2558,23181,5679,1020,31122,4569,6258,17111,6307,1252,5835,14968,4332,5017,2467,11407,15675,8155,7381,15970,872,19634,7,1922,5608,4173,22897,19560,252,1755,18191,5797,8,14428,20206,3370,5007,18988,5375,3030,6111,9705,1804,7760,2712,2276,608,142,308,2047,215,4944,3537,8548,1896,275,1542,7245,3027,342,1290,2484,3323,2,2141,5911,1128,7344,1188,9

In [30]:
#BeautifulSoup
#Beautiful Soup is Python library for pulling data
#out of HTML and XML files

from urllib import request
from bs4 import BeautifulSoup

#urlopen() 함수로 기상청의 전국날씨 읽기
target = request.urlopen('https://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnld=108')

#BeautifulSoup을 사용해 웹페이지를 분석 (parser: 문장의 구조 분석·오류 점검 프로그램)
soup = BeautifulSoup(target, 'html.parser')

#location 태그를 찾음 / select() 함수는 여러개를 선택 / select_one() 함수는 원하는 값을 추출
for location in soup.select('location'):
  print('도시:', location.select_one('city').string)
  print('날씨:', location.select_one('wf').string)
  print('최저기온:', location.select_one('tmn').string)
  print('최고기온:', location.select_one('tmx').string)
  print()

/usr/local/lib/python3.10/dist-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(


도시: 서울
날씨: 흐리고 비
최저기온: 18
최고기온: 23

도시: 인천
날씨: 흐리고 비
최저기온: 18
최고기온: 22

도시: 수원
날씨: 흐리고 비
최저기온: 18
최고기온: 23

도시: 파주
날씨: 흐리고 비
최저기온: 17
최고기온: 23

도시: 이천
날씨: 흐리고 비
최저기온: 18
최고기온: 24

도시: 평택
날씨: 흐리고 비
최저기온: 19
최고기온: 25

도시: 춘천
날씨: 흐리고 비
최저기온: 18
최고기온: 23

도시: 원주
날씨: 흐리고 비
최저기온: 18
최고기온: 23

도시: 강릉
날씨: 흐리고 비
최저기온: 20
최고기온: 24

도시: 대전
날씨: 흐리고 비
최저기온: 18
최고기온: 24

도시: 세종
날씨: 흐리고 비
최저기온: 18
최고기온: 25

도시: 홍성
날씨: 흐리고 비
최저기온: 18
최고기온: 24

도시: 청주
날씨: 흐리고 비
최저기온: 19
최고기온: 25

도시: 충주
날씨: 흐리고 비
최저기온: 17
최고기온: 24

도시: 영동
날씨: 흐리고 비
최저기온: 16
최고기온: 25

도시: 광주
날씨: 흐리고 비
최저기온: 19
최고기온: 25

도시: 목포
날씨: 흐리고 비
최저기온: 19
최고기온: 23

도시: 여수
날씨: 흐리고 비
최저기온: 18
최고기온: 22

도시: 순천
날씨: 흐리고 비
최저기온: 18
최고기온: 22

도시: 광양
날씨: 흐리고 비
최저기온: 18
최고기온: 22

도시: 나주
날씨: 흐리고 비
최저기온: 19
최고기온: 23

도시: 전주
날씨: 흐리고 비
최저기온: 19
최고기온: 24

도시: 군산
날씨: 흐리고 비
최저기온: 19
최고기온: 24

도시: 정읍
날씨: 흐리고 비
최저기온: 18
최고기온: 24

도시: 남원
날씨: 흐리고 비
최저기온: 18
최고기온: 24

도시: 고창
날씨: 흐리고 비
최저기온: 19
최고기온: 24

도시: 무주
날씨: 흐리고 비
최저기온: 16
최고기온: 24

도시: 부산
날씨: 흐림
최저기온: 18
최고기온:

In [31]:
import csv

data = []
keys = ['도시', '날씨', '최저기온', '최고기온']
data.append(keys)

for location in soup.select('location'):
  row = []
  row.append(location.select_one('city').string)
  row.append(location.select_one('wf').string)
  row.append(location.select_one('tmn').string)
  row.append(location.select_one('tmx').string)
  data.append(row)

f = open('kma.csv', 'w')
g = csv.writer(f)
g.writerows(data)
f.close()

In [32]:
#module: os
#colab에서 google drive와 연결
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/2023-1st/')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [33]:
#오류(error):
#a.프로그램 실행 전에 발생하는 오류 → 구문 오류 → 프로그램 자체가 실행되지 않음
#b.프로그램 실행 후에 발생하는 오류 → 예외/런타임 오류
print('프로그램이 시작되었습니다.')
A = [1,2,3]
A[1]

프로그램이 시작되었습니다.


2

In [34]:
#예외를 처리하는 방법: 조건문을 사용 또는 try 구문 사용
#조건문 사용:
user_input = input('정수 입력: ')
num_input = int(user_input)
print('원의 둘레:', 2*3.14*num_input)

user_input = input('정수 입력:')
if user_input.isdigit():
  num_input = int(user_input)
  print('원의 둘레:', 2*3.14*num_input)
else:
  print('정수를 입력하지 않았습니다.')

정수 입력: 3
원의 둘레: 18.84
정수 입력:0
원의 둘레: 0.0


In [35]:
# 프로그램을 작성할때 항상 예외적인 상황까지 모두 생각하는 게 좋음 
# 조건문처럼 예외가 발생할 모든 상황을 예측하기 쉽지 않음
# => try/ except 구문을 사용!
# try:
#   예외가 발생할 가능성이 있는 코드
# except:
#   예외가 발생했을 때 실행할 코드

try:
  user_input = input('정수 입력:')
  num_input = int(user_input)
  print('원의 둘레:', 2*3.14*num_input)
except:
  print('정수를 입력하지 않았습니다.')

정수 입력:3
원의 둘레: 18.84


In [36]:
# try:
#   예외가 발생할 가능성이 있는 코드
# except:
#   예외가 발생했을 때 실행할 코드
# else:
#  예외가 발생하지 않았을때 실행할 코드 
try:
  user_input = input('정수 입력:')
  num_input = int(user_input)
except:
  print('정수를 입력하지 않았습니다.')
else:
  print('원의 둘레:', 2*3.14*num_input)

정수 입력:0
원의 둘레: 0.0


In [37]:
# try:
#   예외가 발생할 가능성이 있는 코드
# except:
#   예외가 발생했을 때 실행할 코드
# else:
#  예외가 발생하지 않았을때 실행할 코드 
# finally:
# 무조건 실행할 코드

try:
  user_input = input('정수 입력:')
  num_input = int(user_input)
except:
  print('정수를 입력하지 않았습니다.')
else:
  print('원의 둘레:', 2*3.14*num_input)
finally:
  print('예외이든 아니든 코딩을 마치겠음')

정수 입력:3.14
정수를 입력하지 않았습니다.
예외이든 아니든 코딩을 마치겠음


In [38]:
#Exercise
#input함수를 써서 어떤 숫자를 입력받고, a가 정수이면 a^2+4를 계산하고,
#정수가 아니면 '숫자가 아닙니다'를 프린트하게끔 try/except/else
#써서 코딩하여라. Finally 구문을 추가하여 '정수든 아니든 코딩을 마치겠음'을 추가하세요.

try:
  A = input('숫자 입력: ')
  a = int(A)
except:
  print('정수가 아닙니다.')
else:
  print('정수입니다. a^2+4 =', a**2+4)
finally:
  print('정수든 아니든 코딩을 마치겠음')

숫자 입력: 3.5
정수가 아닙니다.
정수든 아니든 코딩을 마치겠음


In [39]:
# try:
#   예외가 발생할 가능성이 있는 코드
# except 예외의 종류 as 변수:
#   예외가 발생했을 때 실행할 구문
user_input = input('정수 입력: ')
num_input = int(user_input)
print('원의 둘레', 2*3.14*num_input)
#얘는 에러가 나면 멈춤

try:
  user_input = input('정수 입력: ')
  num_input = int(user_input)
  print('원의 둘레:', 2*3.14*num_input)
except Exception as e:
  print(type(e), e)
#<class 'ValueError'>
#얘는 에러가 나면 일단 뒤도 실행하고 어디가 잘못됐는지 알려줌

정수 입력: 3.5


ValueError: ignored

In [40]:
# 예제 -----------------------
list_num = [52, 34, 31,100]
num_input = int(input('정수 입력: '))
print(f'{num_input}번째 요소: {list_num[num_input-1]}')

try:
  num_input = int(input('정수 입력: '))
  print(f'{num_input}번째 요소: {list_num[num_input-1]}')
except Exception as e:
  print(type(e), e)

#정수입력:3.14
#<class 'ValueError'> invalid literal for int() with base 10: '3.14'
#정수입력:5
#<class 'IndexError'> list index out of range

정수 입력: 3
3번째 요소: 31
정수 입력: 3.14
<class 'ValueError'> invalid literal for int() with base 10: '3.14'
