<a href="https://colab.research.google.com/github/202201617/2022/blob/main/%EC%A0%84%EC%82%B0%EC%88%98%ED%95%99_9_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#행렬
A = [[2,7], [3, 4], [6, 1]]
print(len(A))
print(A[0])
print(len(A[0]))

3
[2, 7]
2


In [ ]:
#행렬의 원소곱
A = [[2,7], [3, 4], [6, 1]]
B = [[1,4], [4, -1], [2, 5]]

def element_product(A, B):
  C = []
  m = len(A)
  n = len(A[0])
  for i in range(m):
    D = []
    for j in range(n):
      value = A[i][j]*B[i][j]
      D.append(value)
    C.append(D)
  
  return C

C = element_product(A,B)
print(C)

[[2, 28], [12, -4], [12, 5]]


In [ ]:
# 행렬곱
A = [[2,7], [3,4], [6,1]]
B = [[3, -3, 5], [-1, 2, -1]]

print(len(A))
print(len(A[0]))
print(len(B[0]))

def matrix_mul(A,B):
  C = []
  m = len(A)
  p = len(A[0])
  n = len(B[0])
  for i in range(m):
    D = []
    for j in range(n):
      sum_k = 0
      for k in range(p):
        sum_k += A[i][k]*B[k][j]
      D.append(sum_k)
    C.append(D)
  return C

C = matrix_mul(A,B)
print(C)

3
2
3
[[-1, 8, 3], [5, -1, 11], [17, -16, 29]]


In [ ]:
#Ax=b 풀기
A = [[1, -1, 2, 1], [5, 8, 6, 3], [4, 2, 5, 3], [3, 2, 1, 4]]
B = [2, 10, 3, 1]
x = list(range(0,4)) #[0,1,2,3]

In [ ]:
#Ax=b 풀기
A = [[1, -1, 2, 1], [5, 8, 6, 3], [4, 2, 5, 3], [3, 2, 1, 4]]
b = [2, 10, 3, 1]
x = list(range(0,4)) #[0,1,2,3]

#forward elimination (upper triangular matrix)
for k in range(0,3):
  for i in range(k+1, 4):
    mult = A[i][k]/A[k][k]
    for j in range(k,4):
      A[i][j] = A[i][j] - mult*A[k][j]
    b[i] = b[i]-mult*b[k]

print(A)
print(b)
print('='*20)

#Back substitution
x[3] = b[3]/A[3][3]
for i in range(2, -1, -1):
  sum_j = 0
  for j in range(i+1, 4):
    sum_j += A[i][j]*x[j]
  x[i] = (b[i] - sum_j)/A[i][i]

print('x=', x)

[[1, -1, 2, 1], [0.0, 13.0, -4.0, -2.0], [0.0, 0.0, -1.1538461538461537, -0.07692307692307687], [0.0, 0.0, 0.0, 1.9999999999999998]]
[2, 0.0, -5.0, 10.000000000000002]
x= [-9.000000000000004, 2.0000000000000004, 4.000000000000001, 5.000000000000002]


In [ ]:
def solve(A,b):
  n = len(A)
  for k in range(0,n-1):
    for i in range(k+1, n):
      mult = A[i][k]/A[k][k]
      for j in range(k,n):
        A[i][j] = A[i][j] - mult*A[k][j]
      b[i] = b[i]-mult*b[k]

  x[n-1] = b[n-1]/A[n-1][n-1]
  for i in range(n-2, -1, -1):
    sum_j = 0
    for j in range(i+1, n):
      sum_j += A[i][j]*x[j]
    x[i] = (b[i] - sum_j)/A[i][i] 

  return x

x = list(range(0,3))
A = [[1, -1, 2],
    [5, 8, 6],
    [4, 2, 5]]
b = [2, 10, 3]
x = solve(A,b)

print(x)

[-5.333333333333334, 1.3333333333333335, 4.333333333333334]


In [ ]:
#np.array 이용하여 행렬 계산하기
import numpy as np

A = np.array([[2,7], [3,4], [6,1]])
B = np.array([[1,4], [4, -1], [2,5]])
m = len(A)
n = len(A[0])

#행렬 덧셈, 뺄셈, 곱셈, 스칼라곱, 원소곱, 행렬곱
print(A+B)
print(A-B)
print(2*A)
C = np.multiply(A,B) #원소곱
print(C)
print( )

A = np.array([[2,7], [3,4], [6,1]]) #3*2
B = np.array([[3,-3,5], [-1,2,-1]]) #2*3
C = np.matmul(A,B) #행렬곱
print(C)
print( )

#transpose A^T
A = np.array([[3,-3,5], [-1,2,1], [2,4,5]])
At = np.transpose(A)
print(At)
print( )

#diagonal matrix
D = np.diag(A) #diagonal elements → array
print(D)
print( )
 
D2 = np.diag(np.diag(A))
print(D2)

[[ 3 11]
 [ 7  3]
 [ 8  6]]
[[ 1  3]
 [-1  5]
 [ 4 -4]]
[[ 4 14]
 [ 6  8]
 [12  2]]
[[ 2 28]
 [12 -4]
 [12  5]]

[[ -1   8   3]
 [  5  -1  11]
 [ 17 -16  29]]

[[ 3 -1  2]
 [-3  2  4]
 [ 5  1  5]]

[3 2 5]

[[3 0 0]
 [0 2 0]
 [0 0 5]]


In [ ]:
import numpy as np

#Identity matrix
I = np.identity(3)
print(I)
print( )

#Upper/lower triangular matrix
A = np.array([[3,-3,4], [-1,2,-1], [2,4,5]])
U = np.triu(A)
print(U)
#L = np.trill(A)
#print(L)
print( )

#determinant/inverse/x=A^-1*b
A = np.array([[1.0, -1.0, 2.0], [5.0, 8.0, 6.0], [4.0, 2.0, 5.0]])
D = np.linalg.det(A)
print(D)

Ainv = np.linalg.inv(A)
print(Ainv)
print( )

#Ax=b → x=A^-1*b
b = np.array([2, 10, 3])
Ainv = np.linalg.inv(A)
x = np.matmul(Ainv, b)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 3 -3  4]
 [ 0  2 -1]
 [ 0  0  5]]

-15.000000000000007
[[-1.86666667 -0.6         1.46666667]
 [ 0.06666667  0.2        -0.26666667]
 [ 1.46666667  0.4        -0.86666667]]

[-5.33333333  1.33333333  4.33333333]


In [15]:
#다음시간 숙제
#A = L + D + U

def decomposition(A):
  L = []
  D = []
  U = []

  m = len(A)
  n = len(A[0])

  for i in range(m):
    L_low = []
    D_low = []
    U_low = []
    for j in range(n):
      if i == j:
        L_low.append(0)
        D_low.append(A[i][j])
        U_low.append(0)
      elif i < j:
        L_low.append(0)
        D_low.append(0)
        U_low.append(A[i][j])
      elif j < i:
        L_low.append(A[i][j])
        D_low.append(0)
        U_low.append(0)
    L.append(L_low)
    D.append(D_low)
    U.append(U_low)

    print(L, D, U)

A = [[1, -1, 2, 1], [5, 8, 6, 3], [4, 2, 5, 3], [3, 2, 1, 4]]

decomposition(A)

[[0, 0, 0, 0]] [[1, 0, 0, 0]] [[0, -1, 2, 1]]
[[0, 0, 0, 0], [5, 0, 0, 0]] [[1, 0, 0, 0], [0, 8, 0, 0]] [[0, -1, 2, 1], [0, 0, 6, 3]]
[[0, 0, 0, 0], [5, 0, 0, 0], [4, 2, 0, 0]] [[1, 0, 0, 0], [0, 8, 0, 0], [0, 0, 5, 0]] [[0, -1, 2, 1], [0, 0, 6, 3], [0, 0, 0, 3]]
[[0, 0, 0, 0], [5, 0, 0, 0], [4, 2, 0, 0], [3, 2, 1, 0]] [[1, 0, 0, 0], [0, 8, 0, 0], [0, 0, 5, 0], [0, 0, 0, 4]] [[0, -1, 2, 1], [0, 0, 6, 3], [0, 0, 0, 3], [0, 0, 0, 0]]


In [18]:
A = [[1, -1, 2, 1], [5, 8, 6, 3], [4, 2, 5, 3], [3, 2, 1, 4]]

L = []
D = []
U = []

m = len(A)
n = len(A[0])

for i in range(m):
    L_low = []
    D_low = []
    U_low = []
    for j in range(n):
      if i == j:
        L_low.append(0)
        D_low.append(A[i][j])
        U_low.append(0)
      elif i < j:
        L_low.append(0)
        D_low.append(0)
        U_low.append(A[i][j])
      elif j < i:
        L_low.append(A[i][j])
        D_low.append(0)
        U_low.append(0)
    L.append(L_low)
    D.append(D_low)
    U.append(U_low)

print(L, D, U)

[[0, 0, 0, 0], [5, 0, 0, 0], [4, 2, 0, 0], [3, 2, 1, 0]] [[1, 0, 0, 0], [0, 8, 0, 0], [0, 0, 5, 0], [0, 0, 0, 4]] [[0, -1, 2, 1], [0, 0, 6, 3], [0, 0, 0, 3], [0, 0, 0, 0]]


In [ ]:
# 퀴즈, f(x)=0
# 안보여